---
title: "Hosting Rmds with GitHub Pages"
author: "Me"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_depth: 2
    toc_float: true
    includes:
      in_header: "favicon.html"
---

```{r message=FALSE}
library(ggplot2)
library(plotly)
```

# Step-by-step instructions

* [Make a Github repo](https://docs.github.com/en/get-started/quickstart/create-a-repo#create-a-repository)
* Make an R Markdown file you're proud of and want to share with the world!
* [Knit the .Rmd file to and html document](https://rmarkdown.rstudio.com/articles_intro.html#:~:text=To%20transform%20your%20markdown%20file,in%20the%20new%20file%20format.)
* Name the html document `index.html`
* Get the `index.html` file into your GitHub repo
  * Long term I recommend to find a Git+GitHub tutorial and learn how to interact with git.  It's such a useful skill for so many different things!
    * [here's a great one if you're just getting started with git](https://www.youtube.com/watch?v=BCQHnlnPusY&list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)
  * Short-term you can use the <kbd>Add file</kbd> button followed by clicking <kbd>Upload files</kbd>

* Turn on GitHub pages for the repo by clicking:
  * <kbd>Settings</kbd>
  * <kbd>Pages</kbd> (under the Code and automation section in the sidebar)
  * Find the dropdown menu in the **Branch** section of the page and select "main" (there's a chance you want to select "master")
    * If you're new to GitHub there's probably only one option to choose, choose that one option that's not "None"
* Wait!
* Find your website online at:`https://<your-username>.github.io/<your-repo-name/`
  * For example this repo is at https://github.com/AdamSpannbauer/hosting-Rmds-with-GitHub-Pages/
    * This shows my user name is **`AdamSpannbauer`**
    * This shows my repo name is **`hosting-Rmds-with-GitHub-Pages`**
  * It's published GitHub pages site can is https://adamspannbauer.github.io/hosting-Rmds-with-GitHub-Pages/

# Make your Rmd more fun!

## CSS themes

## Table of contents

## Favicon
